//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusRes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBooking()
        {
            this.tblCancellations = new HashSet<tblCancellation>();
            this.tblReturnTickets = new HashSet<tblReturnTicket>();
        }
    
        public int Index_Book { get; set; }
        public string BookingID { get; set; }
        public string Source_B { get; set; }
        public string Destination_B { get; set; }
        public string StartDate { get; set; }
        public string StartTime { get; set; }
        public string TicketType { get; set; }
        public float TravelFare { get; set; }
        public string PaymentId { get; set; }
        public string CustUsername { get; set; }
        public string EmailId { get; set; }
        public string BusNo { get; set; }
        public string SelectedSeats { get; set; }
    
        public virtual tblBu tblBu { get; set; }
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblUnAuthCustomer tblUnAuthCustomer { get; set; }
        public virtual tblPayment tblPayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCancellation> tblCancellations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReturnTicket> tblReturnTickets { get; set; }
    }
}
