//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusRes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCancellation
    {
        public string PaymentId { get; set; }
        public string BookingId { get; set; }
        public Nullable<float> Refund { get; set; }
        public int Id_ { get; set; }
    
        public virtual tblBooking tblBooking { get; set; }
        public virtual tblPayment tblPayment { get; set; }
    }
}
