//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusRes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReturnTicket
    {
        public string BookingID { get; set; }
        public string Return_data { get; set; }
        public string Return_Time { get; set; }
        public int Id_ { get; set; }
    
        public virtual tblBooking tblBooking { get; set; }
    }
}
